version: '2'

volumes:
  db:
  redis:

networks:
  external:
  internal:

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres@db/postgres
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - HONEYBADGER_API_KEY=${HONEYBADGER_API_KEY}
      - RAILS_ENV=production
    ports:
      - 8081:80
      - 8443:443
    networks:
      internal:
      external:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    networks:
      internal:
