oauth:
  code4lib:
    client_options: {}
    app_id:
    app_secret:

action_mailer:
  default_options: {}
  default_url_options: {}
  smtp_settings: {}

mailers:
  single:
    to:
  digest:
    to:

feeds:
  - http://digital-scholarship.org/digitalkoans/category/digital-library-jobs/feed/
